#!/usr/bin/env node
'use strict';
// doctor-quality — source/tool quality scoring (module only, spec Pillar 5):
// which tools and source hosts produced claims that SURVIVED (still active,
// never downgraded) vs. got verified, downgraded, superseded or retracted.
// Pure derivation from the folded registry; vault-doctor writes the result to
// profiles/source-quality.md (vault data feeding routing decisions, not
// skill prose).
//
// Module API: scoreQuality(claimsMap) -> {tools, hosts, totals}
//             renderProfile(q, generatedDate) -> markdown
//             hostOf(sourceId) -> host slug | '(none)'

function bucket() { return { claims: 0, live: 0, verified: 0, downgraded: 0, superseded: 0, retracted: 0 }; }

function hostOf(source) {
  if (typeof source !== 'string') return '(none)';
  const parts = source.split('--');
  return (parts.length >= 2 && parts[1]) ? parts[1] : '(none)';
}

function tally(b, c, wasDowngraded) {
  b.claims++;
  if (c.status === 'active' && !wasDowngraded) b.live++;
  if (c.provenance === 'externally-verified') b.verified++;
  if (wasDowngraded) b.downgraded++;
  if (c.status === 'superseded') b.superseded++;
  if (c.status === 'retracted') b.retracted++;
}

function scoreQuality(claimsMap) {
  const tools = {}, hosts = {}, totals = bucket();
  for (const c of claimsMap.values()) {
    const wasDowngraded = (typeof c.note === 'string' && /downgraded/.test(c.note))
      || (c.events || []).some((e) => e && e.op === 'downgrade');
    const tKey = String(c.tool || 'unknown');
    const hKey = hostOf(c.source);
    tally(tools[tKey] || (tools[tKey] = bucket()), c, wasDowngraded);
    tally(hosts[hKey] || (hosts[hKey] = bucket()), c, wasDowngraded);
    tally(totals, c, wasDowngraded);
  }
  return { tools, hosts, totals };
}

function table(title, map) {
  const keys = Object.keys(map).sort((a, b) => map[b].claims - map[a].claims || a.localeCompare(b));
  const L = ['## ' + title, '',
    '| ' + title.toLowerCase().replace(/s$/, '') + ' | claims | live | verified | downgraded | superseded | retracted |',
    '|---|---|---|---|---|---|---|'];
  if (!keys.length) L.push('| _none yet_ |  |  |  |  |  |  |');
  for (const k of keys) {
    const b = map[k];
    L.push('| ' + k + ' | ' + b.claims + ' | ' + b.live + ' | ' + b.verified + ' | ' + b.downgraded + ' | ' + b.superseded + ' | ' + b.retracted + ' |');
  }
  return L.join('\n');
}

function renderProfile(q, generatedDate) {
  return ['# Source & tool quality', '',
    '_Generated by the librarian (vault-doctor.js) on ' + generatedDate + ' — derived from claims.jsonl; do not edit._', '',
    table('Tools', q.tools), '', table('Hosts', q.hosts), '',
    '## Machine block', '', '```json',
    JSON.stringify({ v: 1, generated: generatedDate, tools: q.tools, hosts: q.hosts, totals: q.totals }),
    '```', ''].join('\n');
}

module.exports = { scoreQuality, renderProfile, hostOf };
