#!/usr/bin/env node
'use strict';
// vault-views — regenerate the script-owned views: topics/<slug>/topic.md,
// INDEX.md, and DASHBOARD.md. Views are ALWAYS safe to regenerate — everything
// in them derives from the index, the folded claims registry, and immutable run
// artifacts — EXCEPT the '## Notes (human)' section of topic.md, which is
// preserved verbatim (one clobbered annotation ends human browsing forever).
//
//   node vault-views.js --vault <dir> [--topic <slug>]
//
// Module API: regenTopic(vault, slug), regenIndex(vault), regenDashboard(vault, doctorSummary|null)

const fs = require('fs');
const path = require('path');
const lib = require('./vault-lib');

const NOTES_HEADING = '## Notes (human)';

function lastPerSlug(records) {
  const m = new Map();
  for (const r of records) if (r && r.slug) m.set(r.slug, r);
  return m;
}

function listRuns(vault, slug) {
  const dir = path.join(vault, 'topics', slug, 'runs');
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((d) => {
    try { return fs.statSync(path.join(dir, d)).isDirectory(); } catch (_e) { return false; }
  }).sort();
}

function claimLine(c) {
  const meta = [c.provenance, c.confidence, c.date].filter(Boolean).join(' · ');
  const src = c.source ? ' — ' + c.source : '';
  let line = '- [' + meta + '] ' + c.statement + src + ' (' + c.id + ')';
  if (c.contradictedBy.length) {
    line += '\n  - ⚠ contradicted by ' + c.contradictedBy.join(', ') + ' — both stand until a human resolves (/research correct)';
  }
  return line;
}

function regenTopic(vault, slug) {
  const topicDir = path.join(vault, 'topics', slug);
  fs.mkdirSync(topicDir, { recursive: true });
  const topicFile = path.join(topicDir, 'topic.md');

  let notes = NOTES_HEADING + '\n';
  if (fs.existsSync(topicFile)) {
    const old = fs.readFileSync(topicFile, 'utf8');
    // The real notes section is the LAST line-anchored occurrence — the
    // generated boilerplate mentions the heading mid-sentence, and synthesis
    // text could echo it; first-match indexOf would slice from there and
    // duplicate the whole body on every regen.
    const re = /^## Notes \(human\)/gm;
    let m, i = -1;
    while ((m = re.exec(old)) !== null) i = m.index;
    if (i !== -1) notes = old.slice(i);
  }

  const idx = lastPerSlug(lib.readJsonl(path.join(vault, 'index.jsonl')).records).get(slug) || {};
  const { claims } = lib.foldClaims(lib.readJsonl(path.join(vault, 'claims.jsonl')).records);
  const live = [], superseded = [];
  for (const c of claims.values()) {
    if (c.topic !== slug) continue;
    if (c.status === 'active') live.push(c);
    else if (c.status === 'superseded') superseded.push(c);
  }
  live.sort((a, b) => String(a.date).localeCompare(String(b.date)) || String(a.id).localeCompare(String(b.id)));

  const runs = listRuns(vault, slug);
  // "Latest synthesis" = the newest run that HAS one — a freshly allocated or
  // aborted run without synthesis.md must not blank the topic view.
  let latest = null;
  let synthesis = '_No synthesis yet._';
  for (let i = runs.length - 1; i >= 0; i--) {
    const sp = path.join(topicDir, 'runs', runs[i], 'synthesis.md');
    if (fs.existsSync(sp)) { latest = runs[i]; synthesis = fs.readFileSync(sp, 'utf8').trim(); break; }
  }

  const out = [
    '# ' + (idx.title || slug),
    '',
    '_Generated by re-searcher — everything above "' + NOTES_HEADING + '" is regenerated; edit only that section._',
    '',
    '**Scope:** ' + (idx.scope || 'general') + ' · **Updated:** ' + (idx.date || 'unknown') + ' · **Runs:** ' + runs.length,
    '',
    '## Latest synthesis' + (latest ? ' (run ' + latest + ')' : ''),
    '',
    synthesis,
    '',
    '## Live claims',
    '',
    live.length ? live.map(claimLine).join('\n') : '_None registered._',
    '',
  ];
  if (superseded.length) {
    out.push('## Superseded (history preserved)', '',
      superseded.map((c) => '- ~~' + c.statement + '~~ (' + c.id + ' → ' + c.supersededBy.join(', ') + ')').join('\n'), '');
  }
  out.push('## Runs', '',
    runs.length ? runs.map((r) => '- [' + r + '](runs/' + r + '/plan.md)').join('\n') : '_None._',
    '', notes.trimEnd(), '');
  lib.atomicWrite(topicFile, out.join('\n'));
  return topicFile;
}

function regenIndex(vault) {
  const idx = lastPerSlug(lib.readJsonl(path.join(vault, 'index.jsonl')).records);
  const rows = Array.from(idx.values()).sort((a, b) => String(b.date).localeCompare(String(a.date)));
  const lines = ['# Research vault', ''];
  if (!rows.length) lines.push('_No topics yet — run /research <question>._');
  for (const r of rows) {
    lines.push('- [' + (r.title || r.slug) + '](topics/' + r.slug + '/topic.md) — ' + (r.date || '')
      + (r.scope && r.scope !== 'general' ? ' · ' + r.scope : ''));
  }
  lib.atomicWrite(path.join(vault, 'INDEX.md'), lines.join('\n') + '\n');
}

// DASHBOARD.md (spec Pillar 5): the Obsidian home note. Fully generated, no
// human-owned section — always safe to regenerate. doctorSummary (optional)
// is vault-doctor's in-flight result; without it the doctor lines fall back
// to "run the doctor".
function regenDashboard(vault, doctorSummary) {
  const idx = lastPerSlug(lib.readJsonl(path.join(vault, 'index.jsonl')).records);
  const { claims } = lib.foldClaims(lib.readJsonl(path.join(vault, 'claims.jsonl')).records);
  const metrics = lib.readJsonl(path.join(vault, 'metrics.jsonl')).records;

  let active = 0, superseded = 0, retracted = 0;
  const prov = {};
  const contradicted = [];
  for (const c of claims.values()) {
    if (c.status === 'active') {
      active++;
      prov[c.provenance || 'unknown'] = (prov[c.provenance || 'unknown'] || 0) + 1;
      if (c.contradictedBy.length) contradicted.push(c);
    } else if (c.status === 'superseded') superseded++;
    else if (c.status === 'retracted') retracted++;
  }

  const changes = [];
  for (const c of claims.values()) {
    for (const e of c.events) if (e.op === 'supersede') changes.push({ was: c, e });
  }
  changes.sort((a, b) => String(a.e.date || '').localeCompare(String(b.e.date || '')));
  const recentChanges = changes.slice(-5).reverse();

  const runs = [];
  for (const slug of idx.keys()) {
    const dir = path.join(vault, 'topics', slug, 'runs');
    if (!fs.existsSync(dir)) continue;
    for (const r of fs.readdirSync(dir)) if (!r.startsWith('.')) runs.push({ topic: slug, run: r });
  }
  runs.sort((a, b) => a.run.localeCompare(b.run));
  const recentRuns = runs.slice(-5).reverse();

  const recalls = metrics.filter((m) => m && m.kind === 'recall');
  const recallHits = recalls.filter((m) => Array.isArray(m.hits) && m.hits.length).length;
  const nearMisses = metrics.filter((m) => m && m.kind === 'near-miss').length;
  const hitRate = recalls.length ? Math.round(100 * recallHits / recalls.length) : null;

  const byMonth = new Map();
  for (const s of metrics.filter((m) => m && m.kind === 'save')) {
    const mo = String(s.ts || '').slice(0, 7) || 'unknown';
    const b = byMonth.get(mo) || { saves: 0, fresh: 0 };
    b.saves++;
    if (s.fresh) b.fresh++;
    byMonth.set(mo, b);
  }

  const staleTopics = [];
  for (const rec of idx.values()) {
    if ((rec.volatility || 'moving') !== 'moving') continue;
    const t = Date.parse(String(rec.date || ''));
    if (!Number.isNaN(t) && (Date.now() - t) / 86400000 > 30) staleTopics.push(rec.slug + ' (' + rec.date + ')');
  }
  const lastDoctor = metrics.filter((m) => m && m.kind === 'doctor').pop() || null;

  const L = ['# Research Dashboard', '',
    '_Generated by the librarian (vault-doctor.js) — regenerate any time; do not edit._', '',
    '**Vault:** ' + idx.size + ' topics · ' + runs.length + ' runs · claims ' + active + ' active / ' + superseded + ' superseded / ' + retracted + ' retracted', '',
    '**Provenance (active):** ' + (Object.keys(prov).sort().map((k) => k + ' ' + prov[k]).join(' · ') || '_none_'), '',
    '**Recall:** ' + recalls.length + ' recalls · hit rate ' + (hitRate === null ? 'n/a' : hitRate + '%') + ' · ' + nearMisses + ' near-misses', '',
    '## --fresh usage (abandonment canary)', ''];
  if (!byMonth.size) L.push('_No saves recorded._');
  else {
    L.push('| month | saves | --fresh | rate |', '|---|---|---|---|');
    for (const [mo, b] of Array.from(byMonth.entries()).sort()) {
      L.push('| ' + mo + ' | ' + b.saves + ' | ' + b.fresh + ' | ' + Math.round(100 * b.fresh / b.saves) + '% |');
    }
  }

  L.push('', '## Attention', '');
  const attention = [];
  for (const c of contradicted.slice(0, 5)) {
    attention.push('- ⚠ contradicted: ' + String(c.statement).slice(0, 100) + ' (' + c.id + ' ⇄ ' + c.contradictedBy.join(', ') + ')');
  }
  for (const s of staleTopics.slice(0, 5)) attention.push('- ⏳ stale moving topic: ' + s);
  if (doctorSummary && doctorSummary.work) {
    const w = doctorSummary.work;
    const n = (x) => (Array.isArray(x) ? x.length : 0);
    attention.push('- 🩺 doctor backlog: ' + n(w.promote) + ' to promote · ' + n(w.freshness)
      + ' topics to freshness-check · ' + n(w.mine) + ' runs to mine · ' + n(w.contradictions) + ' pairs to judge');
  }
  L.push(attention.length ? attention.join('\n') : '_Nothing needs attention._');

  L.push('', '## Belief changes (then vs now)', '');
  if (!recentChanges.length) L.push('_No supersessions yet._');
  for (const ch of recentChanges) {
    L.push('- ' + (ch.e.date || '?') + ': ~~' + String(ch.was.statement).slice(0, 90) + '~~ → ' + ch.was.supersededBy.join(', '));
  }

  L.push('', '## Recent runs', '');
  if (!recentRuns.length) L.push('_None yet._');
  for (const r of recentRuns) {
    L.push('- [' + r.run + '](topics/' + r.topic + '/runs/' + r.run + '/plan.md) — [' + r.topic + '](topics/' + r.topic + '/topic.md)');
  }
  L.push('', '**Doctor:** ' + (lastDoctor ? 'last run ' + String(lastDoctor.ts).slice(0, 10) : '_never run — see /research doctor_'), '',
    'See [INDEX](INDEX.md).', '');
  const out = path.join(vault, 'DASHBOARD.md');
  lib.atomicWrite(out, L.join('\n'));
  return out;
}

function main() {
  const vi = process.argv.indexOf('--vault');
  const vault = lib.resolveVault(vi !== -1 ? process.argv[vi + 1] : null);
  const ti = process.argv.indexOf('--topic');
  const topicsDir = path.join(vault, 'topics');
  const slugs = ti !== -1 ? [process.argv[ti + 1]]
    : (fs.existsSync(topicsDir) ? fs.readdirSync(topicsDir).filter((s) => !s.startsWith('.')) : []);
  for (const s of slugs) if (s) regenTopic(vault, s);
  regenIndex(vault);
  process.stdout.write(JSON.stringify({ regenerated: slugs.filter(Boolean).length, index: true }) + '\n');
}

if (require.main === module) main();
module.exports = { regenTopic, regenIndex, regenDashboard };
