#!/usr/bin/env node
'use strict';
// vault-init — idempotent vault skeleton + git lifecycle + templates.
// Creates the directory layout, seed files, Obsidian ignore config, and a
// git repo with a commit identity, then prints one JSON line. Also emits the
// plan / task-spec / finding templates (--template) and a permissions
// allowlist snippet (--allowlist) so first contact isn't a prompt storm.
//
//   node vault-init.js [--vault <dir>]                 # create/repair skeleton
//   node vault-init.js --template plan|task-spec|finding
//   node vault-init.js --allowlist
//
// exit 0 ok / 1 error. Init is the ONLY command allowed to create the vault
// dir — every other script fails loud on a missing vault.

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const lib = require('./vault-lib');

const TEMPLATES = {
  plan: `---
topic: <slug>
title: <human title>
scope: general
classification: straightforward|breadth-first|depth-first
session: <session-id-or-anon>
aliases: ["<synonym>", "<synonym>"]
questions: ["<anticipated future question>", "<another>"]
date: <YYYY-MM-DD>
---

# Plan — <human title>

## Question

<the research question, verbatim>

## Decomposition

<one line per agent: role — core objective>

\`\`\`manifest
[{"role": "<agent-role>", "file": "findings/<agent-role>.md"}]
\`\`\`

## Budget & stop criteria

<N agents, ~M tool calls each; stop when ...>
`,
  'task-spec': `You are one research agent in a fan-out. Do exactly this and nothing else.

ROLE: <agent-role>
OBJECTIVE: <one core objective>
SCOPE: <in-scope> / NOT: <out-of-scope>
SOURCES: prefer official docs and primary sources; fetch pages with
  node <skill-dir>/vault-fetch.js <url> --vault <vault-dir>
  (exit 2 = low confidence: try a better URL or note the gap; record every
  sourceId the fetch prints — claims will need them)
OUTPUT: Write (one Write tool call) your full raw findings to
  <run-dir>/findings/<agent-role>.md
  using the finding template (node <skill-dir>/vault-init.js --template finding),
  at least 500 bytes of real content. Then return ONLY a summary of at most
  2000 characters plus the file path.
`,
  finding: `---
role: <agent-role>
run: <run-id>
task: <one-line task restatement>
date: <YYYY-MM-DD>
---

# Findings — <agent-role>

## Summary

<3-6 sentences>

## Details

<the full raw findings: quotes, data, URLs, dead ends — everything>

## Sources

- <sourceId or URL> — <one line on what it contributed>

## Gaps

- <what you could not establish, and why>
`,
};

const ALLOWLIST = `Add to ~/.claude/settings.json under "permissions" > "allow" (adjust the vault path if you moved it):
  "Write(~/research-vault/**)",
  "Bash(node *vault-init.js*)",
  "Bash(node *vault-fetch.js*)",
  "Bash(node *vault-save.js*)",
  "Bash(node *vault-search.js*)",
  "Bash(node *vault-harvest.js*)",
  "Bash(node *vault-doctor.js*)",
  "Bash(node *vault-redact.js*)",
  "Bash(node *vault-export.js*)"
`;

function arg(name, dflt) {
  const i = process.argv.indexOf(name);
  return i !== -1 ? process.argv[i + 1] : dflt;
}

function main() {
  if (process.argv.includes('--allowlist')) { process.stdout.write(ALLOWLIST); return; }
  if (process.argv.includes('--template')) {
    const tpl = arg('--template', null);
    if (!tpl || !TEMPLATES[tpl]) { process.stderr.write('unknown template: ' + tpl + ' (plan | task-spec | finding)\n'); process.exit(1); }
    process.stdout.write(TEMPLATES[tpl]);
    return;
  }

  const vault = lib.resolveVault(arg('--vault', null), { mustExist: false });
  const created = !fs.existsSync(path.join(vault, 'index.jsonl'));
  // init mutates without the vault lock BY CHOICE: it is the only writer of a not-yet-announced vault, and must work before .lock/'s parent exists (fail-soft).
  for (const d of ['topics', 'sources/raw', 'attachments', 'profiles', '.obsidian']) {
    fs.mkdirSync(path.join(vault, d), { recursive: true });
  }
  for (const f of ['index.jsonl', 'claims.jsonl', 'metrics.jsonl', 'inbox.jsonl', 'wayback-queue.jsonl']) {
    const p = path.join(vault, f);
    if (!fs.existsSync(p)) fs.writeFileSync(p, '');
  }
  const indexMd = path.join(vault, 'INDEX.md');
  if (!fs.existsSync(indexMd)) lib.atomicWrite(indexMd, '# Research vault\n\n_No topics yet — run /research <question>._\n');
  const dash = path.join(vault, 'DASHBOARD.md');
  if (!fs.existsSync(dash)) lib.atomicWrite(dash, '# Dashboard\n\n_Generated by the librarian (stage 3). Nothing here yet._\n\nSee [INDEX](INDEX.md).\n');
  const obs = path.join(vault, '.obsidian', 'app.json');
  if (!fs.existsSync(obs)) lib.atomicWrite(obs, JSON.stringify({ userIgnoreFilters: ['sources/raw/', '.lock/', 'attachments/'] }, null, 2) + '\n');

  let git = 'absent';
  try {
    execFileSync('git', ['--version'], { stdio: 'pipe' });
    if (!fs.existsSync(path.join(vault, '.git'))) {
      execFileSync('git', ['-C', vault, 'init', '-q'], { stdio: 'pipe' });
      git = 'initialized';
    } else git = 'already';
    // auto-commits need an identity; set a repo-local one only if none resolves
    try { execFileSync('git', ['-C', vault, 'config', 'user.email'], { stdio: 'pipe' }); }
    catch (_e) {
      execFileSync('git', ['-C', vault, 'config', 'user.name', 're-searcher'], { stdio: 'pipe' });
      execFileSync('git', ['-C', vault, 'config', 'user.email', 're-searcher@local'], { stdio: 'pipe' });
    }
    const c = lib.gitCommit(vault, created ? 'research: vault init' : 'research: vault repair');
    if (c.warning) process.stderr.write('vault-init: ' + c.warning + '\n');
  } catch (_e) {
    process.stderr.write('vault-init: git not found — vault works, but auto-commit history is disabled\n');
  }

  process.stdout.write(JSON.stringify({ status: created ? 'created' : 'exists', vault, git }) + '\n');
  process.stderr.write('tip: node vault-init.js --allowlist prints a permissions snippet for smoother runs\n');
}

main();
