#!/usr/bin/env node
'use strict';
// vault-views — regenerate the script-owned views: topics/<slug>/topic.md and
// INDEX.md. Views are ALWAYS safe to regenerate — everything in them derives
// from the index, the folded claims registry, and immutable run artifacts —
// EXCEPT the '## Notes (human)' section of topic.md, which is preserved
// verbatim (one clobbered annotation ends human browsing forever).
//
//   node vault-views.js --vault <dir> [--topic <slug>]
//
// Module API: regenTopic(vault, slug), regenIndex(vault)

const fs = require('fs');
const path = require('path');
const lib = require('./vault-lib');

const NOTES_HEADING = '## Notes (human)';

function lastPerSlug(records) {
  const m = new Map();
  for (const r of records) if (r && r.slug) m.set(r.slug, r);
  return m;
}

function listRuns(vault, slug) {
  const dir = path.join(vault, 'topics', slug, 'runs');
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((d) => {
    try { return fs.statSync(path.join(dir, d)).isDirectory(); } catch (_e) { return false; }
  }).sort();
}

function claimLine(c) {
  const meta = [c.provenance, c.confidence, c.date].filter(Boolean).join(' · ');
  const src = c.source ? ' — ' + c.source : '';
  let line = '- [' + meta + '] ' + c.statement + src + ' (' + c.id + ')';
  if (c.contradictedBy.length) {
    line += '\n  - ⚠ contradicted by ' + c.contradictedBy.join(', ') + ' — both stand until a human resolves (/research correct)';
  }
  return line;
}

function regenTopic(vault, slug) {
  const topicDir = path.join(vault, 'topics', slug);
  fs.mkdirSync(topicDir, { recursive: true });
  const topicFile = path.join(topicDir, 'topic.md');

  let notes = NOTES_HEADING + '\n';
  if (fs.existsSync(topicFile)) {
    const old = fs.readFileSync(topicFile, 'utf8');
    // The real notes section is the LAST line-anchored occurrence — the
    // generated boilerplate mentions the heading mid-sentence, and synthesis
    // text could echo it; first-match indexOf would slice from there and
    // duplicate the whole body on every regen.
    const re = /^## Notes \(human\)/gm;
    let m, i = -1;
    while ((m = re.exec(old)) !== null) i = m.index;
    if (i !== -1) notes = old.slice(i);
  }

  const idx = lastPerSlug(lib.readJsonl(path.join(vault, 'index.jsonl')).records).get(slug) || {};
  const { claims } = lib.foldClaims(lib.readJsonl(path.join(vault, 'claims.jsonl')).records);
  const live = [], superseded = [];
  for (const c of claims.values()) {
    if (c.topic !== slug) continue;
    if (c.status === 'active') live.push(c);
    else if (c.status === 'superseded') superseded.push(c);
  }
  live.sort((a, b) => String(a.date).localeCompare(String(b.date)) || String(a.id).localeCompare(String(b.id)));

  const runs = listRuns(vault, slug);
  // "Latest synthesis" = the newest run that HAS one — a freshly allocated or
  // aborted run without synthesis.md must not blank the topic view.
  let latest = null;
  let synthesis = '_No synthesis yet._';
  for (let i = runs.length - 1; i >= 0; i--) {
    const sp = path.join(topicDir, 'runs', runs[i], 'synthesis.md');
    if (fs.existsSync(sp)) { latest = runs[i]; synthesis = fs.readFileSync(sp, 'utf8').trim(); break; }
  }

  const out = [
    '# ' + (idx.title || slug),
    '',
    '_Generated by re-searcher — everything above "' + NOTES_HEADING + '" is regenerated; edit only that section._',
    '',
    '**Scope:** ' + (idx.scope || 'general') + ' · **Updated:** ' + (idx.date || 'unknown') + ' · **Runs:** ' + runs.length,
    '',
    '## Latest synthesis' + (latest ? ' (run ' + latest + ')' : ''),
    '',
    synthesis,
    '',
    '## Live claims',
    '',
    live.length ? live.map(claimLine).join('\n') : '_None registered._',
    '',
  ];
  if (superseded.length) {
    out.push('## Superseded (history preserved)', '',
      superseded.map((c) => '- ~~' + c.statement + '~~ (' + c.id + ' → ' + c.supersededBy.join(', ') + ')').join('\n'), '');
  }
  out.push('## Runs', '',
    runs.length ? runs.map((r) => '- [' + r + '](runs/' + r + '/plan.md)').join('\n') : '_None._',
    '', notes.trimEnd(), '');
  lib.atomicWrite(topicFile, out.join('\n'));
  return topicFile;
}

function regenIndex(vault) {
  const idx = lastPerSlug(lib.readJsonl(path.join(vault, 'index.jsonl')).records);
  const rows = Array.from(idx.values()).sort((a, b) => String(b.date).localeCompare(String(a.date)));
  const lines = ['# Research vault', ''];
  if (!rows.length) lines.push('_No topics yet — run /research <question>._');
  for (const r of rows) {
    lines.push('- [' + (r.title || r.slug) + '](topics/' + r.slug + '/topic.md) — ' + (r.date || '')
      + (r.scope && r.scope !== 'general' ? ' · ' + r.scope : ''));
  }
  lib.atomicWrite(path.join(vault, 'INDEX.md'), lines.join('\n') + '\n');
}

function main() {
  const vi = process.argv.indexOf('--vault');
  const vault = lib.resolveVault(vi !== -1 ? process.argv[vi + 1] : null);
  const ti = process.argv.indexOf('--topic');
  const topicsDir = path.join(vault, 'topics');
  const slugs = ti !== -1 ? [process.argv[ti + 1]]
    : (fs.existsSync(topicsDir) ? fs.readdirSync(topicsDir).filter((s) => !s.startsWith('.')) : []);
  for (const s of slugs) if (s) regenTopic(vault, s);
  regenIndex(vault);
  process.stdout.write(JSON.stringify({ regenerated: slugs.filter(Boolean).length, index: true }) + '\n');
}

if (require.main === module) main();
module.exports = { regenTopic, regenIndex };
